# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  hotelapi:
    image: hotelapi
    build:
      context: .
      dockerfile: Hotel.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5077:5077
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
